#Artificial Intelligence - COMP9414

---


###Tutorial week 1 - Knowledge representation and reasoning



##Background

Knowledge Representation and Reasoning (KRR) is a fundamental area of AI that focuses on how knowledge about the world can be formally represented and used by a machine to solve complex tasks.
This discipline intertwines the cognitive aspects of how humans understand and process information with the computational methods necessary for enabling machines to exhibit intelligent behaviour.

In AI systems, the integration of knowledge representation and reasoning capabilities allows for the development of intelligent agents that can operate autonomously in complex environments.
For instance, KRR is essential in natural language processing (NLP) for understanding and generating human language by associating linguistic input with world knowledge.

###Rule-based Systems

A rule-based system is a type of computer system that leverages domain-specific knowledge in the form of predefined rules.
In any field or domain, there exists a body of specialised knowledge that experts use to solve problems or make decisions. This knowledge encompasses facts, relationships, constraints, and patterns relevant to that domain.
In a rule-based system, this domain-specific knowledge is captured and represented in the form of rules.
For example, in the medical domain, knowledge about symptoms, diseases, and their relationships might be represented.

Rules form the backbone of a rule-based system.
These rules are expressed in the form of "if-then" statements, also known as production rules.
Each rule consists of two parts: the antecedent (the "if" part) and the consequent (the "then" part).
The antecedent specifies the conditions or criteria that must be met for the rule to be applied, while the consequent specifies the action or conclusion to be taken if the conditions are met.
Rules encode the logical relationships, decision criteria, or problem-solving strategies relevant to the domain.

Rule-based systems can effectively solve problems, make decisions, or provide recommendations within their designated domain.
These systems are particularly useful in domains where expertise can be codified into explicit rules, such as expert systems, diagnostic systems, decision support systems, and natural language processing applications.
For instance, a rule-based system might assist a doctor in choosing a diagnosis based on symptoms, or select tactical moves to play a game.

###Knowledge Representation

At its core, knowledge representation is about encoding information about the world in a form that a computer system can utilise to solve complex tasks such as diagnosing a medical condition, carrying out natural language conversations, or navigating in a dynamic environment. It involves defining the structure and semantics of information, such as objects, events, and their relationships, using languages and frameworks like logic, semantic networks, and frames.

The choice of representation significantly impacts a system's ability to reason about the world. For instance, logical representations, such as first-order logic, provide a powerful and expressive language for capturing facts and rules about the world but may be computationally intensive. Alternatively, more heuristic-based representations might offer computational efficiency at the expense of expressiveness.

###Reasoning

Reasoning is the process by which a system derives conclusions or makes decisions based on the knowledge it possesses. In KRR, reasoning typically involves inference mechanisms that apply logical rules to the knowledge base to generate new knowledge or verify the consistency of the existing knowledge.

Various reasoning techniques exist, including deductive reasoning, where conclusions are drawn from general rules; inductive reasoning, which involves generalising from specific instances; and abductive reasoning, which infers the most likely explanations for given data. Each of these reasoning strategies can be applied depending on the nature of the problem and the available knowledge.


##Environments

###Mountain Car Environment

For this tutorial, we will use the gymnasium library.
This is a well-known library regularly used for reinforcement learning environments.
In particular, we will use the Mountain Car environment and create a simple rule-based system to control the car movement.

The Mountain Car is a control problem in which a car is located on a unidimensional track between two steep hills.
The car starts at a random position at the bottom of the valley ($-0.6 < x < 0.4$) with no velocity ($v = 0$).
The aim is to reach the top of the right hill.
However, the car engine does not have enough power to claim to the top directly and, therefore, needs to build momentum moving toward the left hill first.
An agent controlling the car movements observes two state variables, namely, the position $x$ and the velocity $v$.
The position $x$ varies between $-1.2$ and $0.6$ in the x-axis (with $x=-0.53$ the lowest height) and the velocity $v$ between -0.07 and 0.07.
The agent can take three different actions: accelerate the car to the left (0), do not accelerate (1), and accelerate the car to the right (2).
The task is completed in case the top of the right hill is climbed ($x \geq 0.5$) or if the length of the episode is 200 iterations in which case the episode is forcibly terminated.

Gymnasium environments provide access to the environment action and observation spaces.
The following code initialises an environment while visually rendering the output (be aware that rendering the output might not be available on platforms such as Colab).
Next, a random action is selected and performed in the environment for a predetermined number of iterations.


>import gymnasium as gym

>env = gym.make("MountainCar-v0", render_mode="human")

>observation, info = env.reset()

>for _ in range(1000):

>>    action = env.action_space.sample()

>>    observation, reward, terminated, truncated, info = env.step(action)

>>    if terminated or truncated:

>>>    observation, info = env.reset()

>env.close()

###Sudoku

Sudoku is a popular logic-based number puzzle that challenges individuals to fill a $9\times9$ grid such that each row, column, and $3\times3$ subgrid contains all digits from 1 to 9 without repetition.
The puzzle, which draws on the principles of Latin squares developed by Leonhard Euler, begins with a partially completed grid, and the task is to logically deduce the placement of the remaining numbers.

Sudoku's appeal and complexity have garnered attention in various academic fields.
In mathematics, the puzzle is often explored within combinatorial design theory, focusing on its structural properties and the uniqueness of solutions.
In computer science, Sudoku is widely used as a test case for algorithms addressing constraint satisfaction problems, and KRR.
Additionally, cognitive scientists study Sudoku to gain insights into human problem-solving behaviour, particularly in understanding how people approach and resolve complex logical challenges.



__Section 3.1.1.__ Using Python, create the Mountain Car environment using Gymnasium, then start resetting the environment. Gymnasium needs swig and box2d packages, therefore, before creating the environment you should run the following:.

In [ ]:
!pip install swig
!pip install gymnasium[box2d]

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 7.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 953.9/953.9 kB 8.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 374.4/374.4 kB 12.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for box2d-py: filename=box2d_py-2.3.5-cp310-cp310-linux_x86_64.whl size=2376134 sha256=536cbb1b29d016f25e91b4c9d9ca493f8b5183d99c38aa4e45891041de4b30b2
  Stored in directory: /root/.cache/pip/wheels/db/8f/6a/eaaadf056fba10a98d986f6dce954e6201ba3126926fc5ad9e
Successfully built box2d-py


In [ ]:
import gymnasium as gym
env = gym.make("MountainCar-v0")
observation, info = env.reset()
print("Starting Mountain Car environment")

Starting Mountain Car environment


__Section 3.1.2.__ Create a loop with an adequate number of iterations to run the simulation.

__Section 3.1.3.__ Select a random action and execute it in the environment. Observe how the car position varies over time.

In [ ]:
#Section 3.2
for i in range(200):
    #Section 3.3
    action = env.action_space.sample()
    observation, reward, terminated, truncated, info = env.step(action)
    #print(observation) #if visual rendering not available

    if terminated or truncated:
        observation, info = env.reset()
        break

print("Finished in %i steps"%i)
env.close()

Finished in 199 steps


__Section 3.1.4.__ Instead of selecting a random action, select accelerating the car to the right at each time step.

In [ ]:
for i in range(200):
    action = 2
    observation, reward, terminated, truncated, info = env.step(action)
    #print(observation) #if visual rendering not available

    if terminated or truncated:
        observation, info = env.reset()
        break

print("Finished in %i steps"%i)
env.close()

Finished in 199 episodes


__Section 3.1.5__ As the car needs to build momentum, let's create two simple rules as follows:

* Accelerate the car to the right if it is climbing the hill to the right while increasing the velocity.
* Accelerate the car to the left if it is climbing the hill to the left while decreasing the velocity.

In [ ]:
for i in range(200):
    if observation[0] > -0.53 and observation[1] > 0:
      action = 2
    elif observation[0] < -0.53 and observation[1] < 0:
      action = 0
    else:
      action = 1 #or maybe a random action

    observation, reward, terminated, truncated, info = env.step(action)
    #print(observation) #if visual rendering not available

    if terminated or truncated:
        observation, info = env.reset()
        break

print("Finished in %i steps"%i)
env.close()

Finished in 160 episodes


__Section 3.1.6.__ Let's expand our knowledge base by adding two more rules, as follows:

* Accelerate the car to the right if it is climbing the hill to the right while increasing the velocity.
* Accelerate the car to the left if it is climbing the hill to the left while decreasing the velocity.
* Accelerate the car to the right if it is descending the hill to the left while increasing the velocity.
* Accelerate the car to the left if it is descending the hill to the right while decreasing the velocity.

In [ ]:
for i in range(200):
    if observation[0] > -0.53 and observation[1] > 0:
      action = 2
    elif observation[0] < -0.53 and observation[1] < 0:
      action = 0
    elif observation[0] < -0.53 and observation[1] > 0:
      action = 2
    elif observation[0] > -0.53 and observation[1] < 0:
      action = 0
    else:
      action = 1 #or maybe a random action

    observation, reward, terminated, truncated, info = env.step(action)
    #print(observation) #if visual rendering not available

    if terminated or truncated:
        observation, info = env.reset()
        break

print("Finished in %i steps"%i)
env.close()

Finished in 85 episodes


__Section 3.1.7.__ For the previous setups, i.e., always accelerating to the right, two rules knowledge base, and four rules knowledge base, run the experiment 100 times and show the results using boxplots.

In [ ]:
#See tutorial1a.py code in Moodle

__Section 3.2.1__ Implement the Sudoku in Python considering as the initial state the figure shown to the left.

In [ ]:
import numpy as np

# Define the Sudoku grid
matrix = [
    [5, 3, 0, 0, 7, 0, 0, 0, 0],
    [6, 0, 0, 1, 9, 5, 0, 0, 0],
    [0, 9, 8, 0, 0, 0, 0, 6, 0],
    [8, 0, 0, 0, 6, 0, 0, 0, 3],
    [4, 0, 0, 8, 0, 3, 0, 0, 1],
    [7, 0, 0, 0, 2, 0, 0, 0, 6],
    [0, 6, 0, 0, 0, 0, 2, 8, 0],
    [0, 0, 0, 4, 1, 9, 0, 0, 5],
    [0, 0, 0, 0, 8, 0, 0, 7, 9]
]

# Convert the matrix to a NumPy array
grid = np.array(matrix)

# Print the Sudoku grid
def print_sudoku(grid):
    for row in grid:
        print(row)

print("Initial Sudoku Grid:")
print_sudoku(grid)

Initial Sudoku Grid:
[5 3 0 0 7 0 0 0 0]
[6 0 0 1 9 5 0 0 0]
[0 9 8 0 0 0 0 6 0]
[8 0 0 0 6 0 0 0 3]
[4 0 0 8 0 3 0 0 1]
[7 0 0 0 2 0 0 0 6]
[0 6 0 0 0 0 2 8 0]
[0 0 0 4 1 9 0 0 5]
[0 0 0 0 8 0 0 7 9]


__Section 3.2.2__ Can you explain all the knowledge and constraints in Sudoku?


1. Each cell contains a number from 1 to 9.
2. Each number appears exactly once in each row.
3. Each number appears exactly once in each column.
4. Each number appears exactly once in each 3x3 sub-grid.

__Section 3.2.3__ Encode all conditions in Sudoku one by one.



In [ ]:
# 1. Ensure each number appears exactly once in each row, ignoring zeros.
def row_constraint(grid, row):
    row_values = grid[row, :]
    return len(set(row_values) - {0}) == len(row_values) - list(row_values).count(0)

# 2. Ensure each number appears exactly once in each column, ignoring zeros.
def column_constraint(grid, col):
    col_values = grid[:, col]
    return len(set(col_values) - {0}) == len(col_values) - list(col_values).count(0)

# 3. Ensure each number appears exactly once in each 3x3 sub-grid, ignoring zeros.
def subgrid_constraint(grid, row, col):
    subgrid = grid[row//3*3:row//3*3+3, col//3*3:col//3*3+3]
    subgrid_values = subgrid.flatten()
    return len(set(subgrid_values) - {0}) == len(subgrid_values) - list(subgrid_values).count(0)

# Combine all constraints
def is_valid_sudoku(grid):
    for i in range(9):
        if not row_constraint(grid, i):
            return 'Sudoku structure is not valid'
        if not column_constraint(grid, i):
            return 'Sudoku structure is not valid'
        for j in range(0, 9, 3):
            if not subgrid_constraint(grid, i, j):
                return 'Sudoku structure is not valid'
    return 'Sudoku structure is valid'

# Check the validity of the Sudoku grid
print(is_valid_sudoku(grid))


Sudoku structure is valid


__Section 3.2.4__ Can you indicate whether each condition in Sudoku is deductive, inductive, or abductive?



  __Answer:__ all of them are deductive reasoning.

__Section 3.2.5__ Develop an algorithm that can solve Sudoku based on KRR.


In [ ]:
# Check if a move is valid
def is_valid_move(grid, row, col, num):
    grid[row, col] = num
    valid = (row_constraint(grid, row) and
             column_constraint(grid, col) and
             subgrid_constraint(grid, row, col))
    grid[row, col] = 0  # Reset cell after checking
    return valid

# Find an empty location in the grid
def find_empty_location(grid):
    for row in range(9):
        for col in range(9):
            if grid[row, col] == 0:
                return (row, col)
    return None

# Solve the Sudoku puzzle using backtracking
def solve_sudoku(grid):
    empty_loc = find_empty_location(grid)
    if not empty_loc:
        return True  # Puzzle solved

    row, col = empty_loc
    for num in range(1, 10):
        if is_valid_move(grid, row, col, num):
            grid[row, col] = num
            if solve_sudoku(grid):
                return True
            grid[row, col] = 0  # Reset cell and backtrack

    return False

__Section 3.2.6__ Print the final solved puzzle.


In [ ]:
if solve_sudoku(grid):
    print("\nSolved Sudoku:")
    print_sudoku(grid)
else:
    print("No solution exists")


Solved Sudoku:
[5 3 4 6 7 8 9 1 2]
[6 7 2 1 9 5 3 4 8]
[1 9 8 3 4 2 5 6 7]
[8 5 9 7 6 1 4 2 3]
[4 2 6 8 5 3 7 9 1]
[7 1 3 9 2 4 8 5 6]
[9 6 1 5 3 7 2 8 4]
[2 8 7 4 1 9 6 3 5]
[3 4 5 2 8 6 1 7 9]


__Section 3.2.7__ Under what conditions there is no solution for the problem?


1. Insufficient Clues: If the puzzle has too few clues (initially filled cells), it might not be possible to find a unique solution or any solution at all. A Sudoku puzzle typically requires a minimum number of clues to ensure a unique solution.

2. Impossible Configuration: Some puzzles are designed with configurations that are inherently unsolvable due to the constraints they impose, even though they might not immediately appear to be invalid. These puzzles might not be solvable using standard solving techniques.

__Section 3.2.8__ Can you come up with a Sudoku configuration that is impossible to be solved?


In [ ]:
# Too long run-time in my system to find the solution.

impossible_configuration= unsolvable_matrix = [
    [2, 0, 0, 9, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 6, 0],
    [0, 0, 0, 0, 0, 1, 0, 0, 0],
    [5, 0, 2, 6, 0, 0, 4, 0, 7],
    [0, 0, 0, 8, 0, 4, 1, 0, 0],
    [0, 0, 0, 0, 9, 8, 0, 2, 3],
    [0, 0, 0, 0, 0, 3, 0, 8, 0],
    [0, 0, 5, 0, 1, 0, 0, 0, 0],
    [0, 0, 7, 0, 0, 0, 0, 0, 0]
]

grid = np.array(impossible_configuration)

# Print the Sudoku grid
def print_sudoku(grid):
    for row in grid:
        print(row)

print("Initial Sudoku Grid:")
print_sudoku(grid)

if solve_sudoku(grid):
    print("\nSolved Sudoku:")
    print_sudoku(grid)
else:
    print("No solution exists")

Initial Sudoku Grid:
[2 0 0 9 0 0 0 0 0]
[0 0 0 0 0 0 0 6 0]
[0 0 0 0 0 1 0 0 0]
[5 0 2 6 0 0 4 0 7]
[0 0 0 8 0 4 1 0 0]
[0 0 0 0 9 8 0 2 3]
[0 0 0 0 0 3 0 8 0]
[0 0 5 0 1 0 0 0 0]
[0 0 7 0 0 0 0 0 0]
No solution exists
